config/routes.rb
Mushrooms::Application.routes.draw do
  resources :mushrooms
  
  get "mushrooms/new"

  get "pages/home"
  
  get "pages/about"
  
  get "pages/search"
  
  get "mushrooms/search"

  match '/about',   :to => 'pages#about'
  
  match '/addmushroom',  :to => 'mushrooms#new'
  
  match '/viewall', 	:to => 'mushrooms#index'
  
  match '/search',	:to => 'pages#search'
  
  match '/searchmushroom', :to => 'mushrooms#search'
  
  root :to => 'pages#home'
end

app/models/mushroom.rb
class Mushroom < ActiveRecord::Base

	attr_accessible :color, :name, :mushroom_type, :poisonous

	validates :color, :presence => true,
					  :length => { :maximum => 50 }
	validates :name, :presence => true,
					 :length => { :maximum => 50 },
					 :uniqueness => { :case_sensitive => false }
	validates :mushroom_type, :presence => true,
					 :length => { :maximum => 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController
  def new
	@title = "Add New Mushroom"
	@mushroom = Mushroom.new
  end
  
  def show
    @mushroom = Mushroom.find(params[:id])
	@title = @mushroom.name
  end
  
  def create
    @mushroom = Mushroom.new(params[:mushroom])
    if @mushroom.save
      redirect_to @mushroom
    else
      @title = "Add New Mushroom"
      render 'new'
    end
  end
  
  def index
	@title = "All Mushrooms"
	@mushrooms = Mushroom.paginate(:page => params[:page])
  end
  
  def search
	
	star = "%"
	query = ""
	
	@name = params[:name]
	if @name != nil && !@name.empty?
		query = query + "name LIKE '" + star + @name + star + "'"	
	end
	
	@color = params[:color]
	if @color != nil && !@color.empty?
		if query != ""
			query = query + "and color LIKE '" + star + @color + star + "'"
		else 
			query = query + "color LIKE '" + star + @color + star + "'"
		end
	end
	
	@type = params[:type]
	if @type != nil && !@type.empty?
		if query != ""
			query = query + "and mushroom_type LIKE '" + star + @type + star + "'"
		else 
			query = query + "mushroom_type LIKE '" + star + @type + star + "'"
		end
	end
	
	@poisonous = params[:poisonous]
	if @poisonous != nil && !@poisonous.empty?
		if query != ""
			query = query + "and poisonous = '" + @poisonous + "'"
		else 
			query = query + "poisonous = '" + @poisonous + "'"
		end
	end
	
	@mushrooms = Mushroom.where(query)
	
	
	respond_to do |format|
		format.html
		format.json { render :json => @mushrooms }
	end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
	@title = "About"
  end
  
  def home
	@title = "Home"
  end
  
  def search
	@title = "Search"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis.               # Documentation comment
	def title                                           # Method definition
		base_title = "Mushrooms Inc."  # Variable assignment
		if @title.nil?                                    # Boolean test for nil
			base_title                                      # Implicit return
		else
			"#{base_title} | #{@title}"                     # String interpolation
		end
	end
end

app/helpers/mushrooms_helper.rb
module MushroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li>&copy; Not copyrighted</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("mushrooms.jpg", :alt => "Mushroom Inc.", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Add Mushroom", addmushroom_path %></li>
	  <li><%= link_to "View All Mushrooms", viewall_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_scripts.html.erb
<script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
<%= javascript_include_tag 'search.js' %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
	<%= render 'layouts/scripts' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/mushrooms/index.html.erb
<h1>All Mushrooms</h1>
<%= will_paginate %>
<ul class="mushrooms">
  <% @mushrooms.each do |mushroom| %>
    <li>
      <%= link_to mushroom.name, mushroom %>
    </li>
  <% end %>
</ul>

app/views/mushrooms/new.html.erb
<h1>Add Mushrooms</h1>

<%= form_for(@mushroom) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :mushroom_type %><br />
    <%= f.text_field :mushroom_type %>
  </div>
  <div class="field">
    <%= f.label :poisonous %><br />
	<%= f.radio_button :poisonous, "1", :checked => true %> True
	<%= f.radio_button :poisonous, "0" %> False
  </div>
  <div class="actions">
    <%= f.submit "Add this mushroom" %>
  </div>
<% end %>

app/views/mushrooms/search.html.erb
<h1>All Mushrooms</h1>
<ul class="mushrooms">
  <% @mushrooms.each do |mushroom| %>
    <li>
      <%= link_to mushroom.name, mushroom %>
    </li>
  <% end %>
</ul>

app/views/mushrooms/show.html.erb
<h1>Name: <%= @mushroom.name %></h1>
<p>Color: <%= @mushroom.color %></p>
<p>Type: <%= @mushroom.mushroom_type %></p>
<p>Poisonous: <%= @mushroom.poisonous %></p>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We deal in the best mushrooms in the town.</p>

app/views/pages/home.html.erb
<h1>Welcome to Mushrooms Inc.</h1>

<p>
  The home for all of your favorite mushrooms.
</p>
<p>
  Please click "Search" below to find your mushroom...
</p>

<%= link_to "Search", search_path, :class => "search_button round" %>

app/views/pages/search.html.erb
<h1>Search</h1>

<p>
	Please enter the mushroom you want to search for...
</p>

<form>
	<div class="field">
		<label for="searchBox">Name</label><br />
		<input type="text" class="searchBox" id="nameSB" size="40" autocomplete="off" />
		<div id="name_suggest" class="suggestBox">
	</div>
	<div class="field">
		<label for="searchBox">Color</label><br />
		<input type="text" class="searchBox" id="colorSB" size="40" autocomplete="off" />
		<div id="color_suggest" class="suggestBox">
	</div>
	<div class="field">
		<label for="searchBox">Type</label><br />
		<input type="text" class="searchBox" id="typeSB" size="40" autocomplete="off" />
		<div id="type_suggest" class="suggestBox">
	</div>
	<div class="field">
		<label for="searchBox">Poisonous</label>
		<input type="radio" name="poisonousRB" value="t" /> True
		<input type="radio" name="poisonousRB" value="f" /> False
	</div>

	<div class="actions">
		<input type="submit" id="submit" class="search_button round" value="Search" />
	</div>
</form>

<div id="result">
</div>

app/views/shared/_error_messages.html.erb
<% if @mushroom.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@mushroom.errors.count, "error") %> 
        prohibited this mushroom from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @mushroom.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>